version: "3.9"

services:
  migrhelp-web:
    image: nginx
    restart: always
    volumes:
      - ./nginx/templates/migrhelp.conf.template:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
  # backend:
  #   build:
  #     context: .dev/backend/.
  #     dockerfile: Dockerfile
  #     args:
  #       UID: ${UID}
  #       GID: ${GID}
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   ports:
  #     - ${BACKEND_PORT}:3000 
  # postgres:
  #   image: postgres:14.2-bullseye
  #   env_file: .env
  # adminer:
  #   image: adminer
  #   ports:
  #     - ${ADMINER_PORT}:8080
  # pgadmin:
  #     image: dpage/pgadmin4
  #     environment:
  #       PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #       PGADMIN_DEFAULT_PASSWORD: admin
  #     ports:
  #       - "8081:80"
